var annotated =
[
    [ "AOLOOPCONTROL_CONF", "structAOLOOPCONTROL__CONF.html", "structAOLOOPCONTROL__CONF" ],
    [ "AOLOOPCONTROL_DM_DISPCOMB_CONF", "structAOLOOPCONTROL__DM__DISPCOMB__CONF.html", "structAOLOOPCONTROL__DM__DISPCOMB__CONF" ],
    [ "AOLOOPCONTROL_DMTURBCONF", "structAOLOOPCONTROL__DMTURBCONF.html", "structAOLOOPCONTROL__DMTURBCONF" ],
    [ "CMD", "structCMD.html", "structCMD" ],
    [ "CMDARGTOKEN", "structCMDARGTOKEN.html", "structCMDARGTOKEN" ],
    [ "complex_double", "structcomplex__double.html", "structcomplex__double" ],
    [ "complex_float", "structcomplex__float.html", "structcomplex__float" ],
    [ "DATA", "structDATA.html", "structDATA" ],
    [ "IMAGE", "structIMAGE.html", "structIMAGE" ],
    [ "IMAGE_KEYWORD", "structIMAGE__KEYWORD.html", "structIMAGE__KEYWORD" ],
    [ "IMAGE_METADATA", "structIMAGE__METADATA.html", "structIMAGE__METADATA" ],
    [ "kdhyperrect", "structkdhyperrect.html", "structkdhyperrect" ],
    [ "kdnode", "structkdnode.html", "structkdnode" ],
    [ "kdres", "structkdres.html", "structkdres" ],
    [ "kdtree", "structkdtree.html", "structkdtree" ],
    [ "LOGSHIM_CONF", "structLOGSHIM__CONF.html", "structLOGSHIM__CONF" ],
    [ "MODULE", "structMODULE.html", "structMODULE" ],
    [ "res_node", "structres__node.html", "structres__node" ],
    [ "savethreadmsg", "structsavethreadmsg.html", "structsavethreadmsg" ],
    [ "symrec", "structsymrec.html", "structsymrec" ],
    [ "THDATA_IMTOTAL", "structTHDATA__IMTOTAL.html", "structTHDATA__IMTOTAL" ],
    [ "VARIABLE", "structVARIABLE.html", "structVARIABLE" ],
    [ "yy_buffer_state", "structyy__buffer__state.html", "structyy__buffer__state" ],
    [ "yy_trans_info", "structyy__trans__info.html", "structyy__trans__info" ],
    [ "yyalloc", "unionyyalloc.html", "unionyyalloc" ],
    [ "YYSTYPE", "unionYYSTYPE.html", "unionYYSTYPE" ],
    [ "ZERNIKE", "structZERNIKE.html", "structZERNIKE" ]
];